### ISSUE TITLE
Xcode crash after startup

### ISSUE THREAD

**Issue by balinghousheng** [inket/update_xcode_plugins#12]
why?

**Comment by inket** [comment]
You need to open the original Xcode 8 at least once before trying to start the unsigned Xcode. Have you done that?

**Comment by ASooner** [comment]
I've done that,still crash

**Comment by inket** [comment]
Can you provide the crash report and the Xcode logs?

**Comment by zhlooking** [comment]
For me it seems that a plugin called KSImageNamed caused the problem, remove it fix the problem.
![screen shot 2016-09-22 at 11 29 05 am](https://cloud.githubusercontent.com/assets/5212377/18736250/d0391782-80b7-11e6-9d41-e674dad29fd6.png)

**Comment by inket** [comment]
@zhlooking Thanks! I guess I should add a notice about plugins causing crashes. Some plugin might also be the cause for #11

**Comment by bartleby** [comment]
+1 macOS Sierra

**Comment by douxinchun** [comment]
Some plugins will ceased the problem.For me, it's ZLGotoSandbox. Open the crash report and find it.

![b05f5e61-230f-4feb-822a-8b4c4ef9db26](https://cloud.githubusercontent.com/assets/4735098/18867519/255c4536-84d7-11e6-9542-f53a3599a4d2.png)

cd /Users/xxxx/Library/Application Support/Alcatraz/Plug-ins  ,remove it.
cd /Users/xxxx/Library/Application Support/Developer/Shared/Xcode/Plug-ins,remove it.
Then,Xcode-unsigned works.

But,the Console output increased a lot of redundant info,like this:
![bb81b941-61cc-48b0-afd4-2a84d6398ed1](https://cloud.githubusercontent.com/assets/4735098/18867845/6bdbda66-84d8-11e6-99fa-2f9f534103e1.png)


It not happened when I open my project by signed Xcode.
When I open the project by  simulater within Xcode-unsigned,it happens.By devices,it not.
I don't konw why.Maybe it caused by CocoaLumberjack.

**Comment by Marviszhao** [comment]
My Xcode crash on ZLGotoSandbox plugin too!  When I delete it, every thing is ok

**Comment by inket** [comment]
Thanks, people! Will update the README to warn about crashes and what might cause them.
