### ISSUE TITLE
Xcode 8 is not recognized

### ISSUE THREAD

**Issue by sebyddd** [inket/update_xcode_plugins#3]
Whenever I run `update_xcode_plugins --unsign`, the following error pops up: `Didn't find any Xcode 8+ installed on your system.`

I have a copy of Xcode 8 (Xcode-beta.app) in the Applications folder. Do you have any idea why it cannot find it's path?

Thanks!

**Comment by inket** [comment]
Is your Spotlight disabled? This uses `mdfind` to find Xcodes on your computer, and when Spotlight is disabled, mdfind doesn't work.





On Thu, Aug 25, 2016 at 6:18 AM +0900, "Sebastian Dobrincu" <notifications@github.com> wrote:





Whenever I run `update_xcode_plugins --unsign`, the following error pops up: `Didn't find any Xcode 8+ installed on your system.`

I have a copy of Xcode 8 (Xcode-beta.app) in the Applications folder. Do you have any idea why it cannot find it's path?

--
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/inket/update_xcode_plugins/issues/3
