### ISSUE TITLE
There is a  Very Terrible Problem

### ISSUE THREAD

**Issue by SteveUXC** [inket/update_xcode_plugins#34]
I do not know what happened. My XCode become very slowly and even close after reinstall plugins. I feel very sad. The problem remains after uninstall plugins by update_code_plugins. My God! I was thinking about whether or not to reinstall the xcode.

**Comment by inket** [comment]
Xcode slowness while saving files could be related to this: https://github.com/inket/update_xcode_plugins/issues/23

If that doesn't fix it, the problem is probably caused by some plugin. So you can try removing the plugins from `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/`

If that still doesn't solve your issue, you can restore Xcode without reinstalling it with the command `update_xcode_plugins --restore`

Of course, reinstalling Xcode is a completely valid option too.

**Comment by SteveUXC** [comment]
Thank U! I have solve it. The plugin can not user in xcode 8. It too bad
